language: java

jdk:
  - openjdk13

sudo: false

env:
  global:
    - CODECOV_TOKEN="6642c4b4-62ea-454a-a479-a0111a5ad1a4"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -sash-2007@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always